INSERT INTO ORGANIZATIONS (ORGANIZATION_NAME,
ORGANIZATION_FULL_NAME,ORGANIZATION_INN,ORGANIZATION_KPP,
ORGANIZATION_ADDRESS,ORGANIZATION_PHONE,ORGANIZATION_IsAlive)
VALUES ('1С:Виктория','ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "1С: ФРАНЧАЙЗИ ВИКТОРИЯ"',
'7706500456','770301001','г.Москва, Пресненская набережная, дом 12, эт 45 пом IIб ком 11','+74957862146',1
);

INSERT INTO ORGANIZATIONS (ORGANIZATION_NAME,
ORGANIZATION_FULL_NAME,ORGANIZATION_INN,ORGANIZATION_KPP,
ORGANIZATION_ADDRESS,ORGANIZATION_PHONE,ORGANIZATION_IsAlive)
VALUES ('АА Независимость','ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "АА НЕЗАВИСИМОСТЬ"'
,'7717120640','774901001','г.Москва, Ярославское шоссе, дом 27','+74956604791',0
);
INSERT INTO OFFICE (OFFICE_NAME,OFFICE_ORGANIZATION_ID, OFFICE_ADDRESS, OFFICE_PHONE,OFFICE_IsAlive)
VALUES ('СКЛАД','2','г.Москва, Ярославское шоссе, дом 27','+74956604791',0
);
INSERT INTO OFFICE (OFFICE_NAME,OFFICE_ORGANIZATION_ID, OFFICE_ADDRESS, OFFICE_PHONE,OFFICE_IsAlive)
VALUES ('МАГАЗИН','2','г.Москва, Ярославское шоссе, дом 27','+74956604792',0
);
INSERT INTO OFFICE (OFFICE_NAME,OFFICE_ORGANIZATION_ID, OFFICE_ADDRESS, OFFICE_PHONE,OFFICE_IsAlive)
VALUES ('РЕМЗОНА','2','г.Москва, Ярославское шоссе, дом 27','+74956604795',0
);
INSERT INTO OFFICE (OFFICE_NAME,OFFICE_ORGANIZATION_ID, OFFICE_ADDRESS, OFFICE_PHONE,OFFICE_IsAlive)
VALUES ('Отдел Программистов','1','г.Москва, Пресненская набережная, дом 12, эт 45 пом IIб ком 11','+74957862146',1
);
INSERT INTO OFFICE (OFFICE_NAME,OFFICE_ORGANIZATION_ID, OFFICE_ADDRESS, OFFICE_PHONE,OFFICE_IsAlive)
VALUES ('Отдел Проектов','1','г.Москва, Пресненская набережная, дом 12, эт 45 пом IIб ком 11','+74957862147',1
);
INSERT INTO OFFICE (OFFICE_NAME,OFFICE_ORGANIZATION_ID, OFFICE_ADDRESS, OFFICE_PHONE,OFFICE_IsAlive)
VALUES ('Отдел Разработчиков','1','г.Москва, Пресненская набережная, дом 12, эт 45 пом IIб ком 11','+74957862149',1
);
INSERT INTO DOCS(DOCS_NAME,DOCS_CODE)
VALUES ('Паспорт РФ','41');
INSERT INTO DOCS(DOCS_NAME,DOCS_CODE)
VALUES ('Паспорт Иностранного Гражданина','54');
INSERT INTO COUNTRIES (COUNTRIES_NAME,COUNTRIES_CODE)
VALUES ('РоссийскаяФедерация','643');
INSERT INTO COUNTRIES (COUNTRIES_NAME,COUNTRIES_CODE)
VALUES ('Германия','276');

INSERT INTO EMPLOYEES (EMPLOYEE_FIRST_NAME,
EMPLOYEE_SECOND_NAME,
EMPLOYEE_LAST_NAME,
EMPLOYEE_OFFIICE_ID,
EMPLOYEE_POSITION,
EMPLOYEE_PHONE,
EMPLOYEE_DOC_NAME,
EMPLOYEE_DOC_NUMBER,
EMPLOYEE_DOC_DATA,
EMPLOYEE_CITIZENSHIP_NAME,
EMPLOYEE_CITIZENSHIP_CODE,
EMPLOYEE_IS_IDENTIFIED)
VALUES ('Иван','Иванович','Иванов','1','Механик','+74956604792','Паспорт','4505','12.12.2012','Российская Федерация','643',0
);